# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4a5906a4c6133e9626ae6304fd16be87532dffa698104824d0ae1c6ec102dc05b45fa9007ca6011ae56f7fd77a7a3eb503976590a8da466684ab02cc252ffe1

test:
  secret_key_base: e835a7c7bf83beca4e658d410d68e8f47cbd8fc0ad41c0dfcfaaf1152ef81d9d6787b493d5e3c1c13453dc264139fd08d160c715bdf26cf0b42ece7a8eac94e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
